### ISSUE TITLE
Tap installing error with MacOS Big Sur beta

### ISSUE THREAD

**Issue by smallpepperz1** [webhippie/homebrew-webhippie#1]
I'm attempting to use this on a MacOS Big Sur (11.0) beta, and when running `brew tap webhippie/webhippie`, I get the following error. I'm by no means a programmer, and am not very familiar with homebrew, and I have no idea how complex the fix would be, but I wanted to give you a heads up

`Error: Invalid formula: /usr/local/Homebrew/Library/Taps/webhippie/homebrew-webhippie/Formula/medialize.rb
medialize: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the webhippie/webhippie tap (not Homebrew/brew or Homebrew/core)
  /usr/local/Homebrew/Library/Taps/webhippie/homebrew-webhippie/Formula/medialize.rb:21`

**Comment by tboerger** [comment]
Thanks for the report, with #2 this issue should be resolved.
